### ISSUE TITLE
ValueError: Field `mpesa_payment` does not exist

### ISSUE THREAD

**Issue by ngethe** [GikonyoBrian/odoo-mpesa#4]
I keep getting this error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\models.py", line 1057, in _validate_fields
    check(self)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 342, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 1083, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\ir\ir_ui_view.py", line 533, in raise_view_error
    raise ValueError(message)
ValueError: Field `mpesa_payment` does not exist

**Comment by gikonyob** [comment]
Try following the solutions on https://www.odoo.com/forum/help-1/question/field-not-found-134559

**Comment by ngethe** [comment]
Thanks
